# Generated by Django 4.0.2 on 2022-02-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Brand_Image', models.ImageField(upload_to='media/Brands')),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_Image', models.ImageField(upload_to='media/Products')),
                ('Product_Disription', models.CharField(max_length=1000)),
                ('Product_Brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
