# Generated by Django 3.2.9 on 2022-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='day_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
